### ISSUE TITLE
problem in runnig  program in if part

### ISSUE THREAD

**Issue by priyanshu3666** [priyanshu3666/Python#1]
#program started
'''taking input from user
n1,n2,n3 are the number'''
n1 = int(input("Enter 1st number"))
n2 = int(input("Enter 2nd number"))
n3 = int(input("Enter 3rd number"))
#method to compare number to be greater
if n1 > n2 && n1 > n3:
    print("The greatest number among them is ",n1)
elif n2 > n3:
    print("The greatest number among them is ",n2)
else :
    print("The greatest number among them is ",n3)
#program ends

**Comment by dbc2201** [comment]
The problem I see with the above program is you are trying to use `&&` in Python. This does not work in Python, the equivalent of this is `and`.  
The above program could be re-written as  
```python
# program started

'''taking input from user
n1,n2,n3 are the number'''

n1 = int(input("Enter 1st number : "))

n2 = int(input("Enter 2nd number : "))

n3 = int(input("Enter 3rd number : "))

# method to compare number to be greater

if (n1 > n2) and (n1 > n3):
	print "The greatest number among them is ", n1
elif (n2 > n3):
	print "The greatest number among them is ", n2
else :
	print "The greatest number among them is ", n3

# program ends
```

**Comment by dbc2201** [comment]
```python
# program started

"""taking input from user
n1,n2,n3 are the number"""

n1 = int(input("Enter 1st number : "))

n2 = int(input("Enter 2nd number : "))

n3 = int(input("Enter 3rd number : "))

# method to compare number to be greater

if (n1 > n2) and (n1 > n3):
    print("The greatest number among them is ", n1)
elif n2 > n3:
    print("The greatest number among them is ", n2)
else:
    print("The greatest number among them is ", n3)

# program ends

```
___
Consistent code with PEP8

**Comment by priyanshu3666** [comment]
@dbc2201 Thanks sir
